"""
Intent definitions for the embedding-based classifier — several example
phrasings per intent, not one canonical form, so the embedding space
around each intent is well-covered and rephrased questions still match.

Phrasings are deliberately generic ("how much X do I have") rather than
naming real products/materials — WHICH specific item was asked about is
never decided here, that's chatbot/entities.py's job, matched fresh
against each business's own live data. This file only decides the
DOMAIN of the question, which is the same across every business type.
"""

INTENTS: dict[str, list[str]] = {
    "runway_check": [
        "what's running low",
        "what's running out",
        "how much flour do I have left",
        "how much do I have left",
        "when will I run out of sugar",
        "when will I run out of stock",
        "material runway",
        "raw material levels",
        "what needs to be reordered soon",
        "stock levels",
        "do I have enough ingredients",
        "do I have enough to make a batch",
        "how many days of stock do I have",
        "what's my inventory situation",
        "am I low on anything",
        "check my materials",
        "how much of this ingredient is left",
    ],
    "reorder_suggestions": [
        "what should I reorder",
        "what should I buy more of",
        "what do I need to restock",
        "what needs restocking",
        "give me a shopping list",
        "what should I order from suppliers",
        "what am I about to run out of",
        "suggest what to reorder",
        "what's below reorder threshold",
    ],
    "product_stock_check": [
        "how many do I have in stock",
        "how much finished stock do I have",
        "how many units are ready to sell",
        "what's my finished goods inventory",
        "how many products do I have ready",
        "do I have any left to sell",
        "how much stock is on the shelf",
    ],
    "production_status": [
        "what did we produce today",
        "what did we make this week",
        "production cost this week",
        "how much did the last batch cost",
        "batch history",
        "how many units did we make",
        "show me recent production",
        "what have we been producing",
        "how many batches this month",
        "what's the cost of making this",
        "how much labor cost on the last batch",
    ],
    "recipe_cost_check": [
        "how much does it cost to make this",
        "what's the recipe for this product",
        "what ingredients go into this",
        "what's the cost per unit",
        "how much material goes into one unit",
        "break down the cost of this product",
    ],
    "dispatch_status": [
        "what's pending delivery",
        "who owes me money",
        "overdue payments",
        "which retailer hasn't paid",
        "outstanding receivables",
        "who hasn't paid yet",
        "what orders are unpaid",
        "show me overdue orders",
        "which retailers are late on payment",
        "how much am I owed",
        "what's my accounts receivable",
        "did this retailer pay",
    ],
    "revenue_check": [
        "how much revenue this week",
        "total sales this month",
        "how much have I sold",
        "what's my total revenue",
        "how many orders this week",
        "show me sales numbers",
    ],
    "profitability_check": [
        "which product makes the most profit",
        "how's my margin this week",
        "is my profit going up or down",
        "which product has low margin",
        "what's my most profitable product",
        "what's my least profitable product",
        "how much profit did I make",
        "show me my profit trend",
        "which product should I stop making",
        "which product should I focus on",
        "what's my overall margin",
    ],
    "alerts_check": [
        "any alerts",
        "what needs my attention",
        "anything urgent",
        "what's critical right now",
        "give me a summary",
        "what should I look at today",
        "anything I'm missing",
    ],
    "capability_check": [
        "what can you do",
        "what can you help with",
        "how do you work",
        "what kind of questions can I ask",
        "help",
    ],
    "greeting": [
        "hello",
        "hi",
        "hey there",
        "good morning",
        "good afternoon",
    ],
    "farewell": [
        "thanks",
        "thank you",
        "that's all",
        "bye",
        "goodbye",
        "ok thanks",
    ],
}
