// Country -> default currency symbol. Currency is stored as a plain
// symbol string (matching Settings > Business Profile and the DB default
// on business.currency, e.g. '₹'), not an ISO code — kept consistent
// with the existing schema rather than introducing a second format.
// Not all 195 UN member states are listed — this covers the large
// majority plus every country explicitly requested. Add more by
// appending { name, code, currency } objects; nothing else needs to change.

export const countryOptions = [
  { name: 'Afghanistan', code: 'AF', currency: '؋' },
  { name: 'Algeria', code: 'DZ', currency: 'د.ج' },
  { name: 'Argentina', code: 'AR', currency: '$' },
  { name: 'Australia', code: 'AU', currency: 'A$' },
  { name: 'Austria', code: 'AT', currency: '€' },
  { name: 'Bangladesh', code: 'BD', currency: '৳' },
  { name: 'Belgium', code: 'BE', currency: '€' },
  { name: 'Bolivia', code: 'BO', currency: 'Bs.' },
  { name: 'Brazil', code: 'BR', currency: 'R$' },
  { name: 'Cambodia', code: 'KH', currency: '៛' },
  { name: 'Cameroon', code: 'CM', currency: 'FCFA' },
  { name: 'Canada', code: 'CA', currency: 'C$' },
  { name: 'Chile', code: 'CL', currency: '$' },
  { name: 'China', code: 'CN', currency: '¥' },
  { name: 'Colombia', code: 'CO', currency: '$' },
  { name: 'Congo (DRC)', code: 'CD', currency: 'FC' },
  { name: 'Costa Rica', code: 'CR', currency: '₡' },
  { name: 'Croatia', code: 'HR', currency: '€' },
  { name: 'Cuba', code: 'CU', currency: '$' },
  { name: 'Czechia', code: 'CZ', currency: 'Kč' },
  { name: 'Denmark', code: 'DK', currency: 'kr' },
  { name: 'Dominican Republic', code: 'DO', currency: 'RD$' },
  { name: 'Ecuador', code: 'EC', currency: '$' },
  { name: 'Egypt', code: 'EG', currency: 'ج.م' },
  { name: 'El Salvador', code: 'SV', currency: '$' },
  { name: 'Ethiopia', code: 'ET', currency: 'Br' },
  { name: 'Fiji', code: 'FJ', currency: 'FJ$' },
  { name: 'Finland', code: 'FI', currency: '€' },
  { name: 'France', code: 'FR', currency: '€' },
  { name: 'Germany', code: 'DE', currency: '€' },
  { name: 'Ghana', code: 'GH', currency: '₵' },
  { name: 'Greece', code: 'GR', currency: '€' },
  { name: 'Guatemala', code: 'GT', currency: 'Q' },
  { name: 'Honduras', code: 'HN', currency: 'L' },
  { name: 'Hong Kong', code: 'HK', currency: 'HK$' },
  { name: 'Hungary', code: 'HU', currency: 'Ft' },
  { name: 'Iceland', code: 'IS', currency: 'kr' },
  { name: 'India', code: 'IN', currency: '₹' },
  { name: 'Indonesia', code: 'ID', currency: 'Rp' },
  { name: 'Iran', code: 'IR', currency: '﷼' },
  { name: 'Iraq', code: 'IQ', currency: 'ع.د' },
  { name: 'Ireland', code: 'IE', currency: '€' },
  { name: 'Israel', code: 'IL', currency: '₪' },
  { name: 'Italy', code: 'IT', currency: '€' },
  { name: 'Ivory Coast', code: 'CI', currency: 'FCFA' },
  { name: 'Jamaica', code: 'JM', currency: 'J$' },
  { name: 'Japan', code: 'JP', currency: '¥' },
  { name: 'Jordan', code: 'JO', currency: 'د.ا' },
  { name: 'Kenya', code: 'KE', currency: 'KSh' },
  { name: 'Kuwait', code: 'KW', currency: 'د.ك' },
  { name: 'Laos', code: 'LA', currency: '₭' },
  { name: 'Lebanon', code: 'LB', currency: 'ل.ل' },
  { name: 'Libya', code: 'LY', currency: 'ل.د' },
  { name: 'Malawi', code: 'MW', currency: 'MK' },
  { name: 'Malaysia', code: 'MY', currency: 'RM' },
  { name: 'Mali', code: 'ML', currency: 'FCFA' },
  { name: 'Mexico', code: 'MX', currency: '$' },
  { name: 'Morocco', code: 'MA', currency: 'د.م.' },
  { name: 'Mozambique', code: 'MZ', currency: 'MT' },
  { name: 'Myanmar', code: 'MM', currency: 'K' },
  { name: 'Namibia', code: 'NA', currency: 'N$' },
  { name: 'Nepal', code: 'NP', currency: '₨' },
  { name: 'Netherlands', code: 'NL', currency: '€' },
  { name: 'New Zealand', code: 'NZ', currency: 'NZ$' },
  { name: 'Nicaragua', code: 'NI', currency: 'C$' },
  { name: 'Nigeria', code: 'NG', currency: '₦' },
  { name: 'North Macedonia', code: 'MK', currency: 'ден' },
  { name: 'Norway', code: 'NO', currency: 'kr' },
  { name: 'Oman', code: 'OM', currency: 'ر.ع.' },
  { name: 'Pakistan', code: 'PK', currency: '₨' },
  { name: 'Panama', code: 'PA', currency: 'B/.' },
  { name: 'Papua New Guinea', code: 'PG', currency: 'K' },
  { name: 'Paraguay', code: 'PY', currency: '₲' },
  { name: 'Peru', code: 'PE', currency: 'S/' },
  { name: 'Philippines', code: 'PH', currency: '₱' },
  { name: 'Poland', code: 'PL', currency: 'zł' },
  { name: 'Portugal', code: 'PT', currency: '€' },
  { name: 'Qatar', code: 'QA', currency: 'ر.ق' },
  { name: 'Romania', code: 'RO', currency: 'lei' },
  { name: 'Russia', code: 'RU', currency: '₽' },
  { name: 'Rwanda', code: 'RW', currency: 'FRw' },
  { name: 'Saudi Arabia', code: 'SA', currency: 'ر.س' },
  { name: 'Senegal', code: 'SN', currency: 'FCFA' },
  { name: 'Serbia', code: 'RS', currency: 'дин.' },
  { name: 'Singapore', code: 'SG', currency: 'S$' },
  { name: 'Slovakia', code: 'SK', currency: '€' },
  { name: 'South Africa', code: 'ZA', currency: 'R' },
  { name: 'South Korea', code: 'KR', currency: '₩' },
  { name: 'Spain', code: 'ES', currency: '€' },
  { name: 'Sri Lanka', code: 'LK', currency: 'Rs' },
  { name: 'Sudan', code: 'SD', currency: 'ج.س.' },
  { name: 'Sweden', code: 'SE', currency: 'kr' },
  { name: 'Switzerland', code: 'CH', currency: 'CHF' },
  { name: 'Taiwan', code: 'TW', currency: 'NT$' },
  { name: 'Tanzania', code: 'TZ', currency: 'TSh' },
  { name: 'Thailand', code: 'TH', currency: '฿' },
  { name: 'Tunisia', code: 'TN', currency: 'د.ت' },
  { name: 'Turkey', code: 'TR', currency: '₺' },
  { name: 'Uganda', code: 'UG', currency: 'USh' },
  { name: 'Ukraine', code: 'UA', currency: '₴' },
  { name: 'United Arab Emirates', code: 'AE', currency: 'د.إ' },
  { name: 'United Kingdom', code: 'GB', currency: '£' },
  { name: 'United States', code: 'US', currency: '$' },
  { name: 'Uruguay', code: 'UY', currency: '$U' },
  { name: 'Uzbekistan', code: 'UZ', currency: "so'm" },
  { name: 'Venezuela', code: 'VE', currency: 'Bs.' },
  { name: 'Vietnam', code: 'VN', currency: '₫' },
  { name: 'Yemen', code: 'YE', currency: '﷼' },
  { name: 'Zambia', code: 'ZM', currency: 'ZK' },
  { name: 'Zimbabwe', code: 'ZW', currency: 'ZiG' },
]