// Country -> default currency symbol + default timezone. Currency is stored
// as a plain symbol string (matching Settings > Business Profile and the DB
// default on business.currency, e.g. '₹'), not an ISO code — kept consistent
// with the existing schema rather than introducing a second format.
//
// timezone is an IANA zone name (matches business.timezone in the DB, e.g.
// 'Asia/Kolkata'). For single-timezone countries this is unambiguous. For
// multi-timezone countries (US, Canada, Russia, Australia, Brazil) this is
// the most common/capital-region zone, picked as a reasonable default since
// onboarding doesn't currently ask for a city — assumption flagged here
// rather than silently baked in. If precision matters later, swap this for
// a city-level picker or browser Intl.DateTimeFormat().resolvedOptions().timeZone
// as a suggested default the user can override.
//
// Not all 195 UN member states are listed — this covers the large
// majority plus every country explicitly requested. Add more by
// appending { name, code, currency, timezone } objects; nothing else needs to change.

export const countryOptions = [
  { name: 'Afghanistan', code: 'AF', currency: '؋', timezone: 'Asia/Kabul' },
  { name: 'Algeria', code: 'DZ', currency: 'د.ج', timezone: 'Africa/Algiers' },
  { name: 'Argentina', code: 'AR', currency: '$', timezone: 'America/Argentina/Buenos_Aires' },
  { name: 'Australia', code: 'AU', currency: 'A$', timezone: 'Australia/Sydney' },
  { name: 'Austria', code: 'AT', currency: '€', timezone: 'Europe/Vienna' },
  { name: 'Bangladesh', code: 'BD', currency: '৳', timezone: 'Asia/Dhaka' },
  { name: 'Belgium', code: 'BE', currency: '€', timezone: 'Europe/Brussels' },
  { name: 'Bolivia', code: 'BO', currency: 'Bs.', timezone: 'America/La_Paz' },
  { name: 'Brazil', code: 'BR', currency: 'R$', timezone: 'America/Sao_Paulo' },
  { name: 'Cambodia', code: 'KH', currency: '៛', timezone: 'Asia/Phnom_Penh' },
  { name: 'Cameroon', code: 'CM', currency: 'FCFA', timezone: 'Africa/Douala' },
  { name: 'Canada', code: 'CA', currency: 'C$', timezone: 'America/Toronto' },
  { name: 'Chile', code: 'CL', currency: '$', timezone: 'America/Santiago' },
  { name: 'China', code: 'CN', currency: '¥', timezone: 'Asia/Shanghai' },
  { name: 'Colombia', code: 'CO', currency: '$', timezone: 'America/Bogota' },
  { name: 'Congo (DRC)', code: 'CD', currency: 'FC', timezone: 'Africa/Kinshasa' },
  { name: 'Costa Rica', code: 'CR', currency: '₡', timezone: 'America/Costa_Rica' },
  { name: 'Croatia', code: 'HR', currency: '€', timezone: 'Europe/Zagreb' },
  { name: 'Cuba', code: 'CU', currency: '$', timezone: 'America/Havana' },
  { name: 'Czechia', code: 'CZ', currency: 'Kč', timezone: 'Europe/Prague' },
  { name: 'Denmark', code: 'DK', currency: 'kr', timezone: 'Europe/Copenhagen' },
  { name: 'Dominican Republic', code: 'DO', currency: 'RD$', timezone: 'America/Santo_Domingo' },
  { name: 'Ecuador', code: 'EC', currency: '$', timezone: 'America/Guayaquil' },
  { name: 'Egypt', code: 'EG', currency: 'ج.م', timezone: 'Africa/Cairo' },
  { name: 'El Salvador', code: 'SV', currency: '$', timezone: 'America/El_Salvador' },
  { name: 'Ethiopia', code: 'ET', currency: 'Br', timezone: 'Africa/Addis_Ababa' },
  { name: 'Fiji', code: 'FJ', currency: 'FJ$', timezone: 'Pacific/Fiji' },
  { name: 'Finland', code: 'FI', currency: '€', timezone: 'Europe/Helsinki' },
  { name: 'France', code: 'FR', currency: '€', timezone: 'Europe/Paris' },
  { name: 'Germany', code: 'DE', currency: '€', timezone: 'Europe/Berlin' },
  { name: 'Ghana', code: 'GH', currency: '₵', timezone: 'Africa/Accra' },
  { name: 'Greece', code: 'GR', currency: '€', timezone: 'Europe/Athens' },
  { name: 'Guatemala', code: 'GT', currency: 'Q', timezone: 'America/Guatemala' },
  { name: 'Honduras', code: 'HN', currency: 'L', timezone: 'America/Tegucigalpa' },
  { name: 'Hong Kong', code: 'HK', currency: 'HK$', timezone: 'Asia/Hong_Kong' },
  { name: 'Hungary', code: 'HU', currency: 'Ft', timezone: 'Europe/Budapest' },
  { name: 'Iceland', code: 'IS', currency: 'kr', timezone: 'Atlantic/Reykjavik' },
  { name: 'India', code: 'IN', currency: '₹', timezone: 'Asia/Kolkata' },
  { name: 'Indonesia', code: 'ID', currency: 'Rp', timezone: 'Asia/Jakarta' },
  { name: 'Iran', code: 'IR', currency: '﷼', timezone: 'Asia/Tehran' },
  { name: 'Iraq', code: 'IQ', currency: 'ع.د', timezone: 'Asia/Baghdad' },
  { name: 'Ireland', code: 'IE', currency: '€', timezone: 'Europe/Dublin' },
  { name: 'Israel', code: 'IL', currency: '₪', timezone: 'Asia/Jerusalem' },
  { name: 'Italy', code: 'IT', currency: '€', timezone: 'Europe/Rome' },
  { name: 'Ivory Coast', code: 'CI', currency: 'FCFA', timezone: 'Africa/Abidjan' },
  { name: 'Jamaica', code: 'JM', currency: 'J$', timezone: 'America/Jamaica' },
  { name: 'Japan', code: 'JP', currency: '¥', timezone: 'Asia/Tokyo' },
  { name: 'Jordan', code: 'JO', currency: 'د.ا', timezone: 'Asia/Amman' },
  { name: 'Kenya', code: 'KE', currency: 'KSh', timezone: 'Africa/Nairobi' },
  { name: 'Kuwait', code: 'KW', currency: 'د.ك', timezone: 'Asia/Kuwait' },
  { name: 'Laos', code: 'LA', currency: '₭', timezone: 'Asia/Vientiane' },
  { name: 'Lebanon', code: 'LB', currency: 'ل.ل', timezone: 'Asia/Beirut' },
  { name: 'Libya', code: 'LY', currency: 'ل.د', timezone: 'Africa/Tripoli' },
  { name: 'Malawi', code: 'MW', currency: 'MK', timezone: 'Africa/Blantyre' },
  { name: 'Malaysia', code: 'MY', currency: 'RM', timezone: 'Asia/Kuala_Lumpur' },
  { name: 'Mali', code: 'ML', currency: 'FCFA', timezone: 'Africa/Bamako' },
  { name: 'Mexico', code: 'MX', currency: '$', timezone: 'America/Mexico_City' },
  { name: 'Morocco', code: 'MA', currency: 'د.م.', timezone: 'Africa/Casablanca' },
  { name: 'Mozambique', code: 'MZ', currency: 'MT', timezone: 'Africa/Maputo' },
  { name: 'Myanmar', code: 'MM', currency: 'K', timezone: 'Asia/Yangon' },
  { name: 'Namibia', code: 'NA', currency: 'N$', timezone: 'Africa/Windhoek' },
  { name: 'Nepal', code: 'NP', currency: '₨', timezone: 'Asia/Kathmandu' },
  { name: 'Netherlands', code: 'NL', currency: '€', timezone: 'Europe/Amsterdam' },
  { name: 'New Zealand', code: 'NZ', currency: 'NZ$', timezone: 'Pacific/Auckland' },
  { name: 'Nicaragua', code: 'NI', currency: 'C$', timezone: 'America/Managua' },
  { name: 'Nigeria', code: 'NG', currency: '₦', timezone: 'Africa/Lagos' },
  { name: 'North Macedonia', code: 'MK', currency: 'ден', timezone: 'Europe/Skopje' },
  { name: 'Norway', code: 'NO', currency: 'kr', timezone: 'Europe/Oslo' },
  { name: 'Oman', code: 'OM', currency: 'ر.ع.', timezone: 'Asia/Muscat' },
  { name: 'Pakistan', code: 'PK', currency: '₨', timezone: 'Asia/Karachi' },
  { name: 'Panama', code: 'PA', currency: 'B/.', timezone: 'America/Panama' },
  { name: 'Papua New Guinea', code: 'PG', currency: 'K', timezone: 'Pacific/Port_Moresby' },
  { name: 'Paraguay', code: 'PY', currency: '₲', timezone: 'America/Asuncion' },
  { name: 'Peru', code: 'PE', currency: 'S/', timezone: 'America/Lima' },
  { name: 'Philippines', code: 'PH', currency: '₱', timezone: 'Asia/Manila' },
  { name: 'Poland', code: 'PL', currency: 'zł', timezone: 'Europe/Warsaw' },
  { name: 'Portugal', code: 'PT', currency: '€', timezone: 'Europe/Lisbon' },
  { name: 'Qatar', code: 'QA', currency: 'ر.ق', timezone: 'Asia/Qatar' },
  { name: 'Romania', code: 'RO', currency: 'lei', timezone: 'Europe/Bucharest' },
  { name: 'Russia', code: 'RU', currency: '₽', timezone: 'Europe/Moscow' },
  { name: 'Rwanda', code: 'RW', currency: 'FRw', timezone: 'Africa/Kigali' },
  { name: 'Saudi Arabia', code: 'SA', currency: 'ر.س', timezone: 'Asia/Riyadh' },
  { name: 'Senegal', code: 'SN', currency: 'FCFA', timezone: 'Africa/Dakar' },
  { name: 'Serbia', code: 'RS', currency: 'дин.', timezone: 'Europe/Belgrade' },
  { name: 'Singapore', code: 'SG', currency: 'S$', timezone: 'Asia/Singapore' },
  { name: 'Slovakia', code: 'SK', currency: '€', timezone: 'Europe/Bratislava' },
  { name: 'South Africa', code: 'ZA', currency: 'R', timezone: 'Africa/Johannesburg' },
  { name: 'South Korea', code: 'KR', currency: '₩', timezone: 'Asia/Seoul' },
  { name: 'Spain', code: 'ES', currency: '€', timezone: 'Europe/Madrid' },
  { name: 'Sri Lanka', code: 'LK', currency: 'Rs', timezone: 'Asia/Colombo' },
  { name: 'Sudan', code: 'SD', currency: 'ج.س.', timezone: 'Africa/Khartoum' },
  { name: 'Sweden', code: 'SE', currency: 'kr', timezone: 'Europe/Stockholm' },
  { name: 'Switzerland', code: 'CH', currency: 'CHF', timezone: 'Europe/Zurich' },
  { name: 'Taiwan', code: 'TW', currency: 'NT$', timezone: 'Asia/Taipei' },
  { name: 'Tanzania', code: 'TZ', currency: 'TSh', timezone: 'Africa/Dar_es_Salaam' },
  { name: 'Thailand', code: 'TH', currency: '฿', timezone: 'Asia/Bangkok' },
  { name: 'Tunisia', code: 'TN', currency: 'د.ت', timezone: 'Africa/Tunis' },
  { name: 'Turkey', code: 'TR', currency: '₺', timezone: 'Europe/Istanbul' },
  { name: 'Uganda', code: 'UG', currency: 'USh', timezone: 'Africa/Kampala' },
  { name: 'Ukraine', code: 'UA', currency: '₴', timezone: 'Europe/Kyiv' },
  { name: 'United Arab Emirates', code: 'AE', currency: 'د.إ', timezone: 'Asia/Dubai' },
  { name: 'United Kingdom', code: 'GB', currency: '£', timezone: 'Europe/London' },
  { name: 'United States', code: 'US', currency: '$', timezone: 'America/New_York' },
  { name: 'Uruguay', code: 'UY', currency: '$U', timezone: 'America/Montevideo' },
  { name: 'Uzbekistan', code: 'UZ', currency: "so'm", timezone: 'Asia/Tashkent' },
  { name: 'Venezuela', code: 'VE', currency: 'Bs.', timezone: 'America/Caracas' },
  { name: 'Vietnam', code: 'VN', currency: '₫', timezone: 'Asia/Ho_Chi_Minh' },
  { name: 'Yemen', code: 'YE', currency: '﷼', timezone: 'Asia/Aden' },
  { name: 'Zambia', code: 'ZM', currency: 'ZK', timezone: 'Africa/Lusaka' },
  { name: 'Zimbabwe', code: 'ZW', currency: 'ZiG', timezone: 'Africa/Harare' },
]