// Deduped list of currency symbols in use across countryOptions.js.
// Shape matches what Settings > Business Profile and OnboardingContext
// read/write: business.currency is stored as the plain symbol string
// (e.g. '₹'), not an ISO code. `value` is that stored symbol; `label`
// is what's shown in the dropdown. Where a symbol is shared by several
// countries (e.g. '$', 'kr', '₨'), the label uses a generic currency
// name rather than picking one country.
//
// Rebuilt 2026-09-09 after currencyOptions.js was accidentally
// overwritten with country data — see countryOptions.js for that.

export const currencyOptions = [
  { value: '؋', label: '؋ Afghani' },
  { value: 'B/.', label: 'B/. Balboa' },
  { value: '฿', label: '฿ Baht' },
  { value: 'Br', label: 'Br Birr' },
  { value: '$', label: '$ Dollar' },
  { value: 'A$', label: 'A$ Australian Dollar' },
  { value: 'C$', label: 'C$ Dollar (Canada/Nicaragua)' },
  { value: 'FJ$', label: 'FJ$ Fijian Dollar' },
  { value: 'HK$', label: 'HK$ Hong Kong Dollar' },
  { value: 'J$', label: 'J$ Jamaican Dollar' },
  { value: 'NT$', label: 'NT$ New Taiwan Dollar' },
  { value: 'NZ$', label: 'NZ$ New Zealand Dollar' },
  { value: 'S$', label: 'S$ Singapore Dollar' },
  { value: '$U', label: '$U Uruguayan Peso' },
  { value: 'Bs.', label: 'Bs. Bolívar/Boliviano' },
  { value: '₡', label: '₡ Colón' },
  { value: '₵', label: '₵ Cedi' },
  { value: 'CHF', label: 'CHF Swiss Franc' },
  { value: 'ден', label: 'ден Denar' },
  { value: 'дин.', label: 'дин. Serbian Dinar' },
  { value: 'د.إ', label: 'د.إ UAE Dirham' },
  { value: 'د.ا', label: 'د.ا Jordanian Dinar' },
  { value: 'د.ت', label: 'د.ت Tunisian Dinar' },
  { value: 'د.ج', label: 'د.ج Algerian Dinar' },
  { value: 'د.ك', label: 'د.ك Kuwaiti Dinar' },
  { value: 'د.م.', label: 'د.م. Moroccan Dirham' },
  { value: '₫', label: '₫ Dong' },
  { value: '€', label: '€ Euro' },
  { value: 'FC', label: 'FC Congolese Franc' },
  { value: 'FCFA', label: 'FCFA CFA Franc' },
  { value: 'FRw', label: 'FRw Rwandan Franc' },
  { value: 'Ft', label: 'Ft Forint' },
  { value: '₲', label: '₲ Guaraní' },
  { value: 'ع.د', label: 'ع.د Iraqi Dinar' },
  { value: 'ج.س.', label: 'ج.س. Sudanese Pound' },
  { value: 'ج.م', label: 'ج.م Egyptian Pound' },
  { value: '₪', label: '₪ Shekel' },
  { value: '₹', label: '₹ Indian Rupee' },
  { value: '₭', label: '₭ Kip' },
  { value: 'Kč', label: 'Kč Koruna' },
  { value: 'kr', label: 'kr Krona/Krone' },
  { value: 'KSh', label: 'KSh Kenyan Shilling' },
  { value: 'ل.د', label: 'ل.د Libyan Dinar' },
  { value: 'ل.ل', label: 'ل.ل Lebanese Pound' },
  { value: 'L', label: 'L Lempira' },
  { value: 'lei', label: 'lei Leu' },
  { value: '£', label: '£ Pound Sterling' },
  { value: 'MK', label: 'MK Kwacha' },
  { value: 'MT', label: 'MT Metical' },
  { value: 'K', label: 'K Kyat/Kina' },
  { value: 'N$', label: 'N$ Namibian Dollar' },
  { value: '₦', label: '₦ Naira' },
  { value: 'ر.ع.', label: 'ر.ع. Omani Rial' },
  { value: 'ر.ق', label: 'ر.ق Qatari Riyal' },
  { value: 'ر.س', label: 'ر.س Saudi Riyal' },
  { value: '﷼', label: '﷼ Rial' },
  { value: 'Q', label: 'Q Quetzal' },
  { value: 'R$', label: 'R$ Real' },
  { value: '₽', label: '₽ Ruble' },
  { value: '₨', label: '₨ Rupee' },
  { value: 'Rs', label: 'Rs Rupee' },
  { value: 'Rp', label: 'Rp Rupiah' },
  { value: '₴', label: '₴ Hryvnia' },
  { value: '₺', label: '₺ Lira' },
  { value: '₩', label: '₩ Won' },
  { value: 'R', label: 'R Rand' },
  { value: 'RD$', label: 'RD$ Dominican Peso' },
  { value: 'RM', label: 'RM Ringgit' },
  { value: '₱', label: '₱ Peso' },
  { value: 'S/', label: 'S/ Sol' },
  { value: "so'm", label: "so'm Som" },
  { value: 'TSh', label: 'TSh Tanzanian Shilling' },
  { value: 'USh', label: 'USh Ugandan Shilling' },
  { value: '¥', label: '¥ Yen/Yuan' },
  { value: 'zł', label: 'zł Zloty' },
  { value: 'ZK', label: 'ZK Zambian Kwacha' },
  { value: 'ZiG', label: 'ZiG Zimbabwe Gold' },
  { value: '৳', label: '৳ Taka' },
  { value: '៛', label: '៛ Riel' },
]